除去列名，行索引，dataframe剩下的就是ndarray，可用下列代码转换

In [ ]:
nd = df.values

跟pandas一样从0开始计算位置

In [ ]:
nd[row, col]
nd[0, 0] # 左上角第一个数据
nd[3, 2] # 第三行第二列
nd[0:3, 1:3] # 0-2行，1到2列
nd[:, 0:3:2] # ：最后一个数字为步长，给出第一列与第三列数据
nd[:, 3] # 第三列全部数据
nd[-1, 1:3] # 最后一行，1-2列

In [1]:
import numpy as np

np.array([2, 3, 4]) # 一维数组,input的是list

array([2, 3, 4])

In [5]:
np.array([(2, 3, 4), (5, 6, 7)]) #二维数组，input 由tuple组成的list


array([[2, 3, 4],
       [5, 6, 7]])

In [4]:
np.array[[2, 3, 4],[5, 6, 7]] # 则会报错

TypeError: 'builtin_function_or_method' object is not subscriptable

In [7]:
np.empty(5) # 创建一维空数组

array([  1.87062952e-077,   3.21450328e+164,   1.85692977e+216,
         1.99392236e-077,   1.60205318e-306])

In [8]:
np.empty((5,4,3)) # 多维空数组

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [9]:
np.empty(5,3) # 多维必须双括号

TypeError: data type not understood

In [10]:
np.ones(5) # 创建全1数组， 还有np.zeros全零数组

array([ 1.,  1.,  1.,  1.,  1.])

In [11]:
np.ones((5, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
np.ones(5,3)

TypeError: data type not understood

In [13]:
np.ones((5, 3), dtype = np.int_) # 指定数组数据类型

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

随机数组，0-1之间均匀分布

In [14]:
np.random.random((5, 4)) # 在包含0但不包含1的范围内随机取值

array([[ 0.53715135,  0.01642861,  0.06384152,  0.22292383],
       [ 0.93274954,  0.76580119,  0.27367171,  0.13904195],
       [ 0.18537957,  0.96648082,  0.71705001,  0.06585369],
       [ 0.25234164,  0.53911508,  0.69629684,  0.9301814 ],
       [ 0.7228076 ,  0.37892422,  0.02060877,  0.6364324 ]])

In [44]:
np.random.random(5)

array([ 0.79643203,  0.093839  ,  0.29670085,  0.07979791,  0.46173059])

In [15]:
np.random.rand(5 ,4) # 同样效果，但参数是输入行与列，而不是turple

array([[ 0.07552017,  0.89807299,  0.93226377,  0.28048522],
       [ 0.08792925,  0.04098301,  0.98325021,  0.60360392],
       [ 0.2219746 ,  0.62997168,  0.43918394,  0.8774473 ],
       [ 0.47966484,  0.75027828,  0.60206704,  0.24770153],
       [ 0.23300366,  0.50212784,  0.72808818,  0.242763  ]])

随机数组，正太分布

In [ ]:
np.random.normal(size = (2, 3)) # 2行3列的正态分布数组， 默认0为均值，1为标准差
np.random.normal(50, 10, size=(2, 3)) # 修改均值为50,标准差为10

随机int

In [16]:
np.random.randint(10)
np.random.randint(0, 10) # 同上，包含0但不包含10的随机单个int
np.random.randint(0, 10, size = 5) # 含5个数字的一维数组
np.random.randint(0, 10, size = (2, 3)) # 二维数组

array([[5, 2, 4],
       [2, 7, 5]])

In [18]:
np.random.randf #随机float, 还有更多分布类型，需要请参考numpy文档


array([[[[0, 4, 0, 1, 5],
         [2, 3, 0, 1, 9],
         [2, 1, 4, 6, 2],
         [2, 0, 1, 3, 2]],

        [[0, 2, 4, 5, 8],
         [4, 2, 3, 7, 0],
         [0, 7, 0, 7, 0],
         [9, 0, 9, 6, 7]],

        [[7, 4, 0, 5, 5],
         [9, 2, 1, 5, 3],
         [6, 2, 2, 0, 3],
         [7, 3, 9, 6, 6]]],


       [[[0, 2, 1, 5, 7],
         [4, 5, 0, 7, 0],
         [9, 2, 8, 2, 6],
         [5, 4, 4, 4, 2]],

        [[2, 3, 5, 9, 4],
         [8, 2, 8, 7, 3],
         [8, 8, 4, 9, 0],
         [8, 8, 4, 3, 3]],

        [[5, 9, 6, 8, 6],
         [4, 7, 5, 9, 5],
         [2, 5, 0, 9, 4],
         [3, 5, 0, 9, 7]]]])

In [19]:
np.shape # 返回形状，例如（5,4）即5行4列
np.shape[0] # 返回行数
np.shape[1] # 返回列数

<function numpy.core.fromnumeric.shape>

In [ ]:
len(np.shape) # 维度数，即元祖长度
np.size # 数组包含的元素数
np.dtype # 数组元素的数据类型

创建一个数组，进行数组的运算

In [20]:
a = np.random.randint(0, 10, size = (5, 4))
a

array([[7, 2, 4, 1],
       [7, 4, 1, 7],
       [5, 1, 1, 8],
       [4, 5, 1, 6],
       [6, 8, 4, 9]])

In [21]:
a.sum() # 数组所有元素和

91

In [22]:
a.sum(axis = 0) # 访问各列元素总和

array([29, 20, 11, 31])

In [23]:
a.sum(axis = 1) # 访问各行元素总和

array([14, 19, 15, 16, 27])

以上是求和，对于max,min,mean也是同样的操作

In [24]:
a.argmax() # 返回数组中最大值的位置，19表示在多维数组第19个，但不直观，所以一般argmax只用于一维数组

19

计算代码所需时间的方式，Python中的time模块

In [25]:
import time

t1 = time.time()
print ('done')
t2 = time.time()
print ('required time is', t2 - t1, 'seconds')

done
required time is 0.0 seconds


In [27]:
nd1 = np.random.random((1000,10000))

python传统方法计算平均值所需时间

In [36]:
def manual_mean(arr):
    sum = 0
    for i in range(0, arr.shape[0]):
        for j in range(0, arr.shape[1]):
            sum = sum + arr[i, j]
    return sum / arr.size

In [37]:
def numpy_mean(arr):
    return arr.mean()

In [38]:
import time
def how_long(func, *args):
    t0 = time.time()
    result = func(*args)
    t1 = time.time()
    return result, t1 - t0

In [39]:
how_long(manual_mean, nd1)
how_long(numpy_mean, nd1)

(0.49997825930263845, 0.01401376724243164)

In [40]:
a

array([[7, 2, 4, 1],
       [7, 4, 1, 7],
       [5, 1, 1, 8],
       [4, 5, 1, 6],
       [6, 8, 4, 9]])

回到a数组，进行修改操作

In [41]:
a[0,0] = 10
a

array([[10,  2,  4,  1],
       [ 7,  4,  1,  7],
       [ 5,  1,  1,  8],
       [ 4,  5,  1,  6],
       [ 6,  8,  4,  9]])

In [42]:
a[0, :] = 2
a

array([[2, 2, 2, 2],
       [7, 4, 1, 7],
       [5, 1, 1, 8],
       [4, 5, 1, 6],
       [6, 8, 4, 9]])

In [43]:
a[0, :]=[1, 2, 3, 4] # input list得到不同的值
a

array([[1, 2, 3, 4],
       [7, 4, 1, 7],
       [5, 1, 1, 8],
       [4, 5, 1, 6],
       [6, 8, 4, 9]])

In [49]:
a = np.random.rand(5)
a

array([ 0.73400568,  0.54547674,  0.94450649,  0.64271   ,  0.78877771])

In [50]:
indices = np.array([1,1,2,3]) # 通过list来获取数值
a[indices]

array([ 0.54547674,  0.54547674,  0.94450649,  0.64271   ])

In [55]:
a[[1,1,2,3]] # 同上，必须双方括号

array([ 0.54547674,  0.54547674,  0.94450649,  0.64271   ])

使用布尔值访问数据

In [56]:
mean = a.mean()
a[a<mean]

array([ 0.54547674,  0.64271   ])

In [57]:
a * 2

array([ 1.46801137,  1.09095348,  1.88901298,  1.28541999,  1.57755541])

In [58]:
a / 2

array([ 0.36700284,  0.27273837,  0.47225325,  0.321355  ,  0.39438885])

In [59]:
b = np.random.rand(5)
b

array([ 0.68765002,  0.00517229,  0.52400282,  0.20878328,  0.31349197])

In [60]:
a + b # 减 乘 除是一样的

array([ 1.4216557 ,  0.55064903,  1.46850931,  0.85149327,  1.10226967])

In [61]:
a * b

array([ 0.50473902,  0.00282136,  0.49492406,  0.1341871 ,  0.24727548])